"""empty message

Revision ID: 69528a91ae63
Revises: b89408edcf7f
Create Date: 2021-01-04 16:44:27.384528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69528a91ae63'
down_revision = 'b89408edcf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
